github issue ops

diff --git a/.github/actions/org-create-announcement/action.yml b/.github/actions/org-create-announcement/action.yml
--- a/.github/actions/org-create-announcement/action.yml
+++ b/.github/actions/org-create-announcement/action.yml
@@ -24,11 +24,19 @@ runs:
     - name: create a new github organization announcement
       shell: bash
       run: |
-        gh api \
-        --method PATCH \
+        data=$(gh api \
+          --method PATCH \
           orgs/${{ inputs.organization }}/announcement \
           --input - <<< '{
             "announcement": ${{ inputs.announcement }},
             "expires_at": ${{ inputs.expires_at }},
             "user_dismissible": ${{ inputs.user_dismissible }}
           }'
+        )
+        if [[ $? -eq 0 ]]; then
+          json_data=$(jq -nc '{ "msg": "annoucement created successfully", "status": "success" }')
+          echo -e "RESULT=$json_data" >> $GITHUB_ENV
+        else
+          json_data=$(jq -nc --argjson error "$data" '{ "msg": "unable to create announcement", "status": "error": $data }')
+          echo -e "RESULT=$json_data" >> $GITHUB_ENV
+        fi
diff --git a/.github/actions/org-get-admin-list/action.yml b/.github/actions/org-get-admin-list/action.yml
--- a/.github/actions/org-get-admin-list/action.yml
+++ b/.github/actions/org-get-admin-list/action.yml
@@ -14,5 +14,13 @@ runs:
     - name: list organization admins
       shell: bash
       run: |
-        owners=$(INSTANCE="$instance" ORG_NAME="$org_name" yq eval '.github_instances[] | select(.instance == env(INSTANCE)) | .organizations[] | select(.name == env(ORG_NAME)) | .owners[]' <<< "$yaml_str")
-}
+        export INSTANCE="${{ inputs.instance }}"
+        export ORG_NAME="${{ inputs.organization }}"
+        data=$(yq eval -M -o=json '[.github_instances[] | select(.instance == env(INSTANCE)) | .organizations[] | select(.name == env(ORG_NAME)) | .owners[]]' ./.github/ENTITLEMENTS/github.yml | jq -c .)
+        if [[ $? -eq 0 ]]; then
+          json_data=$(jq -nc --argjson data "$data" '{ "msg": "org admins successfully retrieved", "status": "success", "data": $data }')
+          echo -e "RESULT=$json_data" >> $GITHUB_ENV
+        else
+          json_data=$(jq -nc --argjson error "$data" '{ "msg": "unable to retrieve org admins", "status": "failure", "error": $data }')
+          echo -e "RESULT=$json_data" >> $GITHUB_ENV
+        fi
diff --git a/.github/actions/repo-create-archive/action.yml b/.github/actions/repo-create-archive/action.yml
--- a/.github/actions/repo-create-archive/action.yml
+++ b/.github/actions/repo-create-archive/action.yml
@@ -1,4 +1,4 @@
-name: repo-create-archive
+name: archive a repository
 inputs:
   instance:
     description: "GitHub Instance"
@@ -16,7 +16,14 @@ runs:
     - name: archive a repository
       shell: bash
       run: |
-        gh api repos/${{ inputs.organization }}/${{ inputs.repository }} \
+        data=$(gh api repos/${{ inputs.organization }}/${{ inputs.repository }} \
           --input - <<< '{
             "archived": true
-          }'
+          }')
+        if [[ $? -eq 0 ]]; then
+          json_data=$(jq -nc '{ "msg": "created repository archive successfully", "status": "success" }')
+          echo -e "RESULT=$json_data" >> $GITHUB_ENV
+        else
+          json_data=$(jq -nc --argjson error "$data" '{ "msg": "unable to create repository archive", "status": "error": $data }')
+          echo -e "RESULT=$json_data" >> $GITHUB_ENV
+        fi
diff --git a/.github/actions/repo-create-webhook/action.yml b/.github/actions/repo-create-webhook/action.yml
--- a/.github/actions/repo-create-webhook/action.yml
+++ b/.github/actions/repo-create-webhook/action.yml
@@ -1,4 +1,4 @@
-name: repo-create-webhook
+name: create an repository webhook
 
 inputs:
   instance:
@@ -29,19 +29,27 @@ inputs:
 runs:
   using: composite
   steps:
-    - name: create an organization webhook
+    - name: create an repository webhook
       shell: bash
       run: |
         active="$([[ "${{ inputs.active }}" == "["Enable"]" ]] && echo true || echo false)"
-        gh api orgs/${{ inputs.organization }}/${{ inputs.repository }}/hooks \
-          --input - << EOF
-          {
-            "name": "web",
-            "active": $active,
-            "events": ${{ inputs.events }},
-            "config": {
-              "url": "${{ inputs.webhook_url }}",
-              "content_type": "${{ inputs.content_type }}"
-            }
+        data=$(gh api orgs/${{ inputs.organization }}/${{ inputs.repository }}/hooks \
+        --input - << EOF
+        {
+          "name": "web",
+          "active": $active,
+          "events": ${{ inputs.events }},
+          "config": {
+            "url": "${{ inputs.webhook_url }}",
+            "content_type": "${{ inputs.content_type }}"
           }
+        }
         EOF
+        )
+        if [[ $? -eq 0 ]]; then
+          json_data=$(jq -nc '{ "msg": "created repository webhook successfully", "status": "success" }')
+          echo -e "RESULT=$json_data" >> $GITHUB_ENV
+        else
+          json_data=$(jq -nc --argjson error "$data" '{ "msg": "unable to create repository webhook", "status": "error": $data }')
+          echo -e "RESULT=$json_data" >> $GITHUB_ENV
+        fi
diff --git a/.github/actions/repo-create/action.yml b/.github/actions/repo-create/action.yml
--- a/.github/actions/repo-create/action.yml
+++ b/.github/actions/repo-create/action.yml
@@ -25,8 +25,15 @@ runs:
     - name: create a repository
       shell: bash
       run: |
-        gh repo create \
+        data=$(gh repo create \
           ${{ inputs.organization }}/${{ inputs.repository }} \
           --${{ inputs.visibility }} \
           `[[ "${{ inputs.readme }}" == "["Enable"]" ]] && echo --add-readme` \
-          --description "${{ inputs.description }}"
+          --description "${{ inputs.description }}")
+        if [[ $? -eq 0 ]]; then
+          json_data=$(jq -nc '{ "msg": "created repository successfully", "status": "success" }')
+          echo -e "RESULT=$json_data" >> $GITHUB_ENV
+        else
+          json_data=$(jq -nc --argjson error "$data" '{ "msg": "unable to create repository", "status": "error": $data }')
+          echo -e "RESULT=$json_data" >> $GITHUB_ENV
+        fi        
diff --git a/.github/actions/repo-toggle-issues/action.yml b/.github/actions/repo-toggle-issues/action.yml
--- a/.github/actions/repo-toggle-issues/action.yml
+++ b/.github/actions/repo-toggle-issues/action.yml
@@ -1,4 +1,4 @@
-name: repo-toggle-issues
+name: toggle repository issues
 
 inputs:
   instance:
@@ -17,9 +17,16 @@ runs:
     - name: toggle repository issues
       shell: bash
       run: |
-        gh api \
+        data=$(gh api \
           --method PATCH \
           repos/${{ inputs.organization }}/${{ inputs.repository }} \
           --input - <<< '{
             "has_issues": true
-          }'
+          }')
+        if [[ $? -eq 0 ]]; then
+          json_data=$(jq -nc '{ "msg": "toggled repository issues successfully", "status": "success" }')
+          echo -e "RESULT=$json_data" >> $GITHUB_ENV
+        else
+          json_data=$(jq -nc --argjson error "$data" '{ "msg": "unable to toggle repository issues", "status": "error": $data }')
+          echo -e "RESULT=$json_data" >> $GITHUB_ENV
+        fi
diff --git a/.github/actions/repo-toggle-visibility/action.yml b/.github/actions/repo-toggle-visibility/action.yml
--- a/.github/actions/repo-toggle-visibility/action.yml
+++ b/.github/actions/repo-toggle-visibility/action.yml
@@ -1,4 +1,4 @@
-name: repo-toggle-visibility
+name: toggle repository visibility
 
 inputs:
   instance:
@@ -20,7 +20,14 @@ runs:
     - name: toggle repository visibility
       shell: bash
       run: |
-        gh api repos/${{ inputs.organization }}/${{ inputs.repository }} \
+        data=$(gh api repos/${{ inputs.organization }}/${{ inputs.repository }} \
           --input - <<< '{
             "visibility": "${{ inputs.visibility }}"
-          }'
+          }')
+        if [[ $? -eq 0 ]]; then
+          json_data=$(jq -nc '{ "msg": "repository visability toggled successfully", "status": "success" }')
+          echo -e "RESULT=$json_data" >> $GITHUB_ENV
+        else
+          json_data=$(jq -nc --argjson error "$data" '{ "msg": "unable to toggle repository visibility", "status": "error": $data }')
+          echo -e "RESULT=$json_data" >> $GITHUB_ENV
+        fi
diff --git a/.github/actions/repo-update-name/action.yml b/.github/actions/repo-update-name/action.yml
--- a/.github/actions/repo-update-name/action.yml
+++ b/.github/actions/repo-update-name/action.yml
@@ -1,4 +1,4 @@
-name: repo-update-name
+name: update a repository name
 
 inputs:
   instance:
@@ -20,7 +20,14 @@ runs:
     - name: update a repository name
       shell: bash
       run: |
-        gh api repos/${{ inputs.organization }}/${{ inputs.repository }} \
+        data=$(gh api repos/${{ inputs.organization }}/${{ inputs.repository }} \
           --input - <<< '{
             "name": "${{ inputs.name }}"
-          }'
+          }')
+        if [[ $? -eq 0 ]]; then
+          json_data=$(jq -nc '{ "msg": "updated repository name successfully", "status": "success" }')
+          echo -e "RESULT=$json_data" >> $GITHUB_ENV
+        else
+          json_data=$(jq -nc --argjson error "$data" '{ "msg": "unable to rename repository", "status": "error": $data }')
+          echo -e "RESULT=$json_data" >> $GITHUB_ENV
+        fi
